Implement Classroom, Book, and Rental Classes with Relationships
MussieTeka/RubySchoolLibrary pull request #3
Opened 2023-06-23 16:20 UTC by MussieTeka

**Classroom Class:**

- Created `Classroom` class with `@label` instance variable initialized in the constructor.
- Implemented setter and getter methods for `@label` using `attr_accessor`.
- Established has-many/belongs-to relationship between `Classroom` and `Student`:
  - Implemented has-many side (classroom has many students).
  - Implemented belongs-to side (student belongs to a classroom).
  - Ensured that adding a student to a classroom sets the classroom for the student.
  - Ensured that setting the classroom for a student also adds the student to the classroom's students.

**Book Class:**

- Created `Book` class with `@title` and `@author` instance variables initialized in the constructor.
- Implemented setter and getter methods for `@title` and `@author` using `attr_accessor`.

**Rental Class:**

- Created `Rental` class with `@date` instance variable initialized in the constructor.
- Implemented setter and getter methods for `@date` using `attr_accessor`.
- Established many-to-many relationship between `Person` and `Book` using `Rental`:
  - Implemented has-many side of Book and Rental (book has many rentals).
  - Implemented belongs-to side of Rental and Book (rental belongs to a book).
  - Implemented has-many side of Person and Rental (person has many rentals).
  - Implemented belongs-to side of Rental and Person (rental belongs to a person).
  - Modified constructor of Rental to set associated Book and Person.

The changes have been thoroughly tested and meet the specified requirements. Thank you for reviewing my work.

2023-06-23 18:15 UTC, Ismailco requested changes
### Hi @MussieTeka, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Required Changes ♻️
- [ ] Kindly make sure to add getters `attr_reader` for the `classroom` variable in the `Student` class.
- [ ] Also make sure a method that serves as the 'belongs-to' side is present in the `Student` class, e.g `def classroom=(classroom).....`

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 18:15 UTC, Ismailco commented on person.rb
> +  attr_reader :id, :rentals
- [ ] Same here kindly consider adding `rentals` to the `attr_accessor` instead of just `attr_reader`

2023-06-23 18:15 UTC, Ismailco commented on person.rb
>    def initialize(id, name = 'Unknown', age = nil, parent_permission: true)
- [ ] The id should be generated automatically, kindly consider removing it from the constructor, also age doesn't have a default value kindly make sure to remove `= nil`

2023-06-23 18:15 UTC, Ismailco commented on person.rb
> +  end
- [ ] Same here for the `add_rentals` method it should use the `Rental` class to create a new rental. Your code should look something like this  👇🏼 
```ruby
def add_rental(book, date) 
  Rental.new(date, book, self)
end
```

2023-06-24 14:20 UTC, MussieTeka commented on classroom.rb
> +    students << student
Thank you for the feedback @Ismailco, I have added the missing `@` before the `students` variable.

2023-06-24 16:19 UTC, MussieTeka commented on person.rb
> +  end
Thank you for your feedback, @Ismailco. I have revised the entire codebase according to the project requirements.

2023-06-24 16:19 UTC, MussieTeka commented on person.rb
>    def initialize(id, name = 'Unknown', age = nil, parent_permission: true)
Thank you for your feedback, @Ismailco. I have revised the entire codebase according to the project requirements.

2023-06-24 16:19 UTC, MussieTeka commented on person.rb
> +  attr_reader :id, :rentals
Thank you for your feedback, @Ismailco. I have revised the entire codebase according to the project requirements.

2023-06-24 16:19 UTC, MussieTeka commented on rental.rb
> +    person.add_rental(self)
Thank you for your feedback, @Ismailco. I have revised the entire codebase according to the project requirements.

2023-06-24 16:19 UTC, MussieTeka commented on rental.rb
> +  attr_reader :book, :person
Thank you for your feedback, @Ismailco. I have revised the entire codebase according to the project requirements.

2023-06-24 16:19 UTC, MussieTeka commented on book.rb
> +  end
Thank you for your feedback, @Ismailco. I have revised the entire codebase according to the project requirements.

2023-06-24 16:19 UTC, MussieTeka commented on book.rb
> +  attr_reader :rentals
Thank you for your feedback, @Ismailco. I have revised the entire codebase according to the project requirements.

2023-06-24 16:35 UTC, alexander16108 approved these changes
Hi @MussieTeka , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/dM2xuxnJCg4H6/giphy.gif"/>

## Highlights
✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-24 18:55 UTC, merged